#!/bin/bash

set -euo pipefail

COMMIT_SHA="${1:-}"
if [ -z "${COMMIT_SHA}" ]; then
  exit 0
fi

ROOT_DIR=$(git rev-parse --show-toplevel 2>/dev/null || true)
if [ -z "${ROOT_DIR}" ]; then
  exit 0
fi

LOG_ROOT="${ROOT_DIR}/.gemini/local-guards"
RUN_ID="$(date +%Y%m%d-%H%M%S)-${COMMIT_SHA:0:8}"
RUN_DIR="${LOG_ROOT}/${RUN_ID}"
mkdir -p "${RUN_DIR}"

CHANGED_FILES_FILE="${RUN_DIR}/changed-files.txt"
DIFF_FILE="${RUN_DIR}/commit.diff"
SUMMARY_FILE="${RUN_DIR}/summary.md"
LATEST_SUMMARY="${LOG_ROOT}/latest-summary.md"
LATEST_POINTER="${LOG_ROOT}/latest-run.txt"

ADVERSARY_PROMPT_FILE="${ROOT_DIR}/.agents/prompts/local-passive-adversary.md"
AUDITOR_PROMPT_FILE="${ROOT_DIR}/.agents/prompts/local-passive-auditor.md"

git -C "${ROOT_DIR}" show --name-only --format= "${COMMIT_SHA}" | sed '/^[[:space:]]*$/d' > "${CHANGED_FILES_FILE}"
git -C "${ROOT_DIR}" show --patch --format= "${COMMIT_SHA}" > "${DIFF_FILE}"

if ! command -v gemini >/dev/null 2>&1; then
  cat > "${SUMMARY_FILE}" <<EOF
## Passive Guard Summary

- Commit: \`${COMMIT_SHA}\`
- Adversary: SKIPPED (gemini CLI not found in PATH)
- Auditor: SKIPPED (gemini CLI not found in PATH)
EOF
  cp "${SUMMARY_FILE}" "${LATEST_SUMMARY}"
  echo "${RUN_DIR}" > "${LATEST_POINTER}"
  exit 0
fi

run_guard() {
  local guard_name="$1"
  local prompt_file="$2"
  local status_file="$3"
  local report_file="$4"
  local raw_log_file="$5"

  if [ ! -f "${prompt_file}" ]; then
    echo "SKIPPED" > "${status_file}"
    cat > "${report_file}" <<EOF
## ${guard_name} Report

Prompt file not found:
\`${prompt_file}\`
EOF
    return 0
  fi

  local prompt_text
  prompt_text=$(cat "${prompt_file}")

  gemini --prompt "${prompt_text}

Execution context:
- Repository root: ${ROOT_DIR}
- Commit SHA: ${COMMIT_SHA}
- Changed files list: ${CHANGED_FILES_FILE}
- Diff file: ${DIFF_FILE}
- Status output path: ${status_file}
- Report output path: ${report_file}

Instructions:
- Read files from given paths.
- Write ONLY PASS or FAIL to status output path.
- Write concise markdown report to report output path.
- Do not modify repository files.
" --yolo > "${raw_log_file}" 2>&1 || true

  if [ ! -f "${status_file}" ]; then
    echo "FAIL" > "${status_file}"
  fi

  local normalized
  normalized=$(tr -d ' \r\n' < "${status_file}" | tr '[:lower:]' '[:upper:]')
  if [ "${normalized}" != "PASS" ] && [ "${normalized}" != "FAIL" ]; then
    echo "FAIL" > "${status_file}"
  else
    echo "${normalized}" > "${status_file}"
  fi

  if [ ! -f "${report_file}" ]; then
    cat > "${report_file}" <<EOF
## ${guard_name} Report

No report generated by Gemini.
EOF
  fi
}

ADVERSARY_STATUS="${RUN_DIR}/adversary.status"
ADVERSARY_REPORT="${RUN_DIR}/adversary.md"
ADVERSARY_RAW_LOG="${RUN_DIR}/adversary.raw.log"

AUDITOR_STATUS="${RUN_DIR}/auditor.status"
AUDITOR_REPORT="${RUN_DIR}/auditor.md"
AUDITOR_RAW_LOG="${RUN_DIR}/auditor.raw.log"

run_guard "Adversary" "${ADVERSARY_PROMPT_FILE}" "${ADVERSARY_STATUS}" "${ADVERSARY_REPORT}" "${ADVERSARY_RAW_LOG}"
run_guard "Auditor" "${AUDITOR_PROMPT_FILE}" "${AUDITOR_STATUS}" "${AUDITOR_REPORT}" "${AUDITOR_RAW_LOG}"

ADVERSARY_VERDICT=$(cat "${ADVERSARY_STATUS}")
AUDITOR_VERDICT=$(cat "${AUDITOR_STATUS}")

cat > "${SUMMARY_FILE}" <<EOF
## Passive Guard Summary

- Commit: \`${COMMIT_SHA}\`
- Adversary: ${ADVERSARY_VERDICT}
- Auditor: ${AUDITOR_VERDICT}

### Artifacts
- Changed files: \`${CHANGED_FILES_FILE}\`
- Diff: \`${DIFF_FILE}\`
- Adversary report: \`${ADVERSARY_REPORT}\`
- Auditor report: \`${AUDITOR_REPORT}\`
EOF

cp "${SUMMARY_FILE}" "${LATEST_SUMMARY}"
echo "${RUN_DIR}" > "${LATEST_POINTER}"
