#!/bin/bash

set -euo pipefail

ROOT_DIR=$(git rev-parse --show-toplevel)
REFS_FILE="${1:-}"
COPILOT_CAVEMAN_MODE="${COPILOT_CAVEMAN_MODE:-full}"
if ! [[ "${COPILOT_CAVEMAN_MODE}" =~ ^(lite|full|ultra|wenyan-lite|wenyan-full|wenyan-ultra)$ ]]; then 
  echo "Invalid COPILOT_CAVEMAN_MODE: ${COPILOT_CAVEMAN_MODE}" >&2; 
  exit 1; 
fi

if [ -z "${REFS_FILE}" ] || [ ! -f "${REFS_FILE}" ]; then
  echo "Missing refs file for pre-push guard runner."
  exit 1
fi

if ! command -v copilot >/dev/null 2>&1; then
  echo "Copilot CLI not found. Install/login Copilot CLI before pushing."
  exit 1
fi

RUN_ID="$(date +%Y%m%d-%H%M%S)"
RUN_DIR="${ROOT_DIR}/.copilot/local-guards/pre-push/${RUN_ID}"
mkdir -p "${RUN_DIR}"

CHANGED_FILES_FILE="${RUN_DIR}/changed-files.txt"
DIFF_FILE="${RUN_DIR}/push.diff"
SUMMARY_FILE="${RUN_DIR}/summary.md"
LATEST_SUMMARY="${ROOT_DIR}/.copilot/local-guards/latest-pre-push-summary.md"
LATEST_POINTER="${ROOT_DIR}/.copilot/local-guards/latest-pre-push-run.txt"

ADVERSARY_PROMPT_FILE="${ROOT_DIR}/.agents/prompts/local-prepush-copilot-adversary.md"
AUDITOR_PROMPT_FILE="${ROOT_DIR}/.agents/prompts/local-prepush-copilot-auditor.md"

is_zero_sha() {
  [[ "$1" =~ ^0+$ ]]
}

is_valid_sha() {
  [[ "$1" =~ ^[0-9a-f]{40}$ ]]
}

collect_push_scope() {
  : > "${CHANGED_FILES_FILE}"
  : > "${DIFF_FILE}"

  while read -r local_ref local_sha remote_ref remote_sha; do
    if [ -z "${local_sha:-}" ] || is_zero_sha "${local_sha}"; then
      continue
    fi

    if ! is_valid_sha "${local_sha}"; then
      echo "Error: Invalid local SHA '${local_sha}'" >&2
      exit 1
    fi

    if [ -n "${remote_sha:-}" ] && ! is_zero_sha "${remote_sha}"; then
      if ! is_valid_sha "${remote_sha}"; then
        echo "Error: Invalid remote SHA '${remote_sha}'" >&2
        exit 1
      fi
      RANGE="${remote_sha}..${local_sha}"
    elif git -C "${ROOT_DIR}" rev-parse --verify "${local_sha}^" >/dev/null 2>&1; then
      RANGE="${local_sha}^..${local_sha}"
    else
      # Root commit: compare against empty tree
      EMPTY_TREE=$(git hash-object -t tree /dev/null)
      RANGE="${EMPTY_TREE}..${local_sha}"
    fi

    if ! git -C "${ROOT_DIR}" diff --name-only "${RANGE}" >> "${CHANGED_FILES_FILE}"; then
      echo "Error: Failed to collect changed files for range ${RANGE}" >&2
      exit 1
    fi
    if ! git -C "${ROOT_DIR}" diff "${RANGE}" >> "${DIFF_FILE}"; then
      echo "Error: Failed to collect diff for range ${RANGE}" >&2
      exit 1
    fi
    echo >> "${DIFF_FILE}"
  done < "${REFS_FILE}"

  sort -u -o "${CHANGED_FILES_FILE}" "${CHANGED_FILES_FILE}"
}

run_guard() {
  local guard_name="$1"
  local prompt_file="$2"
  local status_file="$3"
  local report_file="$4"
  local raw_log_file="$5"

  if [ ! -f "${prompt_file}" ]; then
    echo "FAIL" > "${status_file}"
    cat > "${report_file}" <<EOF
## ${guard_name} Report

Prompt file not found:
\`${prompt_file}\`
EOF
    return
  fi

  local prompt_text
  prompt_text=$(cat "${prompt_file}")
  local caveman_header
  caveman_header=$'/caveman '"${COPILOT_CAVEMAN_MODE}"$'\nUse caveman mode strictly (terse, no filler). If command unsupported, still follow caveman style instructions.\n'

  echo "▶ ${guard_name}: running headless Copilot check..."
  copilot -p "${caveman_header}
${prompt_text}

Execution context:
- Repository root: ${ROOT_DIR}
- Changed files list: ${CHANGED_FILES_FILE}
- Diff file: ${DIFF_FILE}
- Status output path: ${status_file}
- Report output path: ${report_file}

Instructions:
- Read files from given paths.
- Write ONLY PASS or FAIL to status output path.
- Write concise markdown report to report output path.
- Do not modify repository files.
" --add-dir "${ROOT_DIR}" --add-dir "/usr/bin" --add-dir "/bin" --allow-all-paths --allow-tool="write" --allow-tool="shell" --available-tools "view,apply_patch,bash,glob,list_directory" --no-ask-user --silent 2>&1 | tee "${raw_log_file}" || true

  if [ ! -f "${status_file}" ]; then
    echo "FAIL" > "${status_file}"
  fi

  local normalized
  normalized=$(tr -d ' \r\n' < "${status_file}" | tr '[:lower:]' '[:upper:]')
  if [ "${normalized}" != "PASS" ] && [ "${normalized}" != "FAIL" ]; then
    echo "FAIL" > "${status_file}"
  else
    echo "${normalized}" > "${status_file}"
  fi

  if [ ! -f "${report_file}" ]; then
    cat > "${report_file}" <<EOF
## ${guard_name} Report

No report generated by Copilot.
EOF
  fi
}

collect_push_scope

if [ ! -s "${CHANGED_FILES_FILE}" ]; then
  cat > "${SUMMARY_FILE}" <<EOF
## Pre-push Copilot Guard Summary

No changed files detected in push scope.
EOF
  cp "${SUMMARY_FILE}" "${LATEST_SUMMARY}"
  echo "${RUN_DIR}" > "${LATEST_POINTER}"
  exit 0
fi

ADVERSARY_STATUS="${RUN_DIR}/adversary.status"
ADVERSARY_REPORT="${RUN_DIR}/adversary.md"
ADVERSARY_RAW_LOG="${RUN_DIR}/adversary.raw.log"

AUDITOR_STATUS="${RUN_DIR}/auditor.status"
AUDITOR_REPORT="${RUN_DIR}/auditor.md"
AUDITOR_RAW_LOG="${RUN_DIR}/auditor.raw.log"

run_guard "Copilot Adversary" "${ADVERSARY_PROMPT_FILE}" "${ADVERSARY_STATUS}" "${ADVERSARY_REPORT}" "${ADVERSARY_RAW_LOG}"
run_guard "Copilot Auditor" "${AUDITOR_PROMPT_FILE}" "${AUDITOR_STATUS}" "${AUDITOR_REPORT}" "${AUDITOR_RAW_LOG}"

ADVERSARY_VERDICT=$(cat "${ADVERSARY_STATUS}")
AUDITOR_VERDICT=$(cat "${AUDITOR_STATUS}")

cat > "${SUMMARY_FILE}" <<EOF
## Pre-push Copilot Guard Summary

- Adversary: ${ADVERSARY_VERDICT}
- Auditor: ${AUDITOR_VERDICT}

### Artifacts
- Changed files: \`${CHANGED_FILES_FILE}\`
- Diff: \`${DIFF_FILE}\`
- Adversary report: \`${ADVERSARY_REPORT}\`
- Auditor report: \`${AUDITOR_REPORT}\`
EOF

cp "${SUMMARY_FILE}" "${LATEST_SUMMARY}"
echo "${RUN_DIR}" > "${LATEST_POINTER}"

if [ "${ADVERSARY_VERDICT}" != "PASS" ] || [ "${AUDITOR_VERDICT}" != "PASS" ]; then
  echo "❌ Copilot pre-push guard failed. See ${SUMMARY_FILE}"
  exit 1
fi

echo "✅ Copilot pre-push guard passed."
